services:
  - type: web
    name: dash-prod
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python -c "from app import init_db; init_db()" && 
      gunicorn app:server --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: ENV
        value: production
    disk:
      name: data_volume
      mountPath: /data
