services:
  - type: web
    name: dash-prod
    env: python
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python -c "from app import init_db; init_db()"
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PORT
        value: 10000
      - key: ENV
        value: production
    disk:
      name: data_volume
      mountPath: /data
