# render.yaml - 完整生产级配置
services:
  - type: web
    name: dash-production  # 服务名称
    env: python
    region: singapore  # 可选：选择离用户最近的区域(oregon/singapore/frankfurt)
    plan: free  # 免费计划，可选starter/standard等付费计划
    
    # 构建命令
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import init_db; init_db()"
    
    # 启动命令（生产环境推荐gunicorn）
    startCommand: |
      gunicorn app:server \
        --bind 0.0.0.0:$PORT \
        --workers 4 \
        --timeout 120 \
        --worker-class gthread \
        --threads 2
    
    # 环境变量
    envVars:
      - key: ENV
        value: production
      - key: PORT
        value: 10000  # 必须与startCommand中的$PORT对应
      - key: DASH_DEBUG
        value: false
    
    # 持久化存储（SQLite必需）
    disk:
      name: data_volume
      mountPath: /data  # 必须与app.py中的生产环境路径匹配
      sizeGB: 1  # 免费计划最大1GB
    
    # 健康检查（确保应用已就绪）
    healthCheckPath: /_dash-layout
    healthCheckTimeoutSeconds: 30
    
    # 自动部署设置
    autoDeploy: true
    branch: main  # 监听的git分支
    
    # 高级优化参数
    scaling:
      instances: 1  # 免费计划只能1个实例
      memory: 512MB  # 免费计划内存限制
    advanced:
      dockerfilePath: Dockerfile  # 如果用Docker部署
      preDeployCommand: echo "预部署检查完成"
